# Generated by Django 4.2.2 on 2023-12-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bool', models.BooleanField(default=False)),
                ('stripe_checkout_id', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_id', models.CharField(max_length=300)),
                ('userPayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.userpayment')),
            ],
        ),
    ]
