# Generated by Django 4.2.16 on 2025-08-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bool', models.BooleanField(default=False)),
                ('stripe_checkout_id', models.CharField(max_length=500)),
                ('last_stripe_session_id', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('purchase_id', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_id', models.CharField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('userPayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.userpayment')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_plan', models.CharField(default='Trial', max_length=50)),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('billing_amount', models.IntegerField(default=0)),
                ('billing_status', models.CharField(default='pending', max_length=20)),
                ('shopify_charge_id', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
    ]
