# Generated by Django 4.2.2 on 2024-05-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_customuser_last_password_change'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.customuser'),
            preserve_default=False,
        ),
    ]
