# Generated by Django 4.2.16 on 2025-08-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='last_stripe_session_id',
        ),
    ]
