# Generated by Django 4.2.2 on 2023-10-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_id', models.CharField(max_length=300)),
                ('userPayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.userpayment')),
            ],
        ),
    ]
