# Generated by Django 4.2.16 on 2025-07-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_contact_phone_number'),
        ('payments', '0002_stripeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('billing_amount', models.IntegerField(default=0)),
                ('billing_status', models.CharField(default='pending', max_length=20)),
                ('shopify_charge_id', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
    ]
