# Generated by Django 4.2.2 on 2024-05-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_purchase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='purchase_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
