# Generated by Django 4.2.16 on 2025-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_userpayment_last_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='last_stripe_session_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
