# Generated by Django 4.2.16 on 2025-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billing_plan',
            field=models.CharField(default='Trial', max_length=50),
        ),
    ]
