# Generated by Django 4.2.2 on 2023-12-23 16:07

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_alter_message_message_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_tracking_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('sender', models.CharField(max_length=20)),
                ('sms_text', models.TextField(max_length=500)),
                ('content_link', models.URLField(blank=True, max_length=500, null=True)),
                ('sms_sends', models.IntegerField(default=0)),
                ('total_bounce_rate', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('total_overall_rate', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('total_views', models.IntegerField(default=0)),
                ('click_number', models.IntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('delivered', models.IntegerField(default=0)),
                ('unsubscribe_path', models.CharField(default='https://sendit-frontend-production.up.railway.app/opt-out', max_length=100)),
                ('not_delivered', models.IntegerField(default=0)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contactlist')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
    ]
