# Generated by Django 4.2.2 on 2023-10-16 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sender', models.CharField(max_length=20)),
                ('sms_text', models.TextField(max_length=500)),
                ('content_link', models.URLField(blank=True, max_length=500, null=True)),
                ('sms_sends', models.IntegerField(default=0)),
                ('click_number', models.IntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('delivered', models.IntegerField(default=0)),
                ('scheduled', models.BooleanField(default=False)),
                ('not_delivered', models.IntegerField(default=0)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contactlist')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
    ]
