# Generated by Django 4.2.2 on 2023-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms_text',
            field=models.TextField(max_length=500),
        ),
    ]
