# Generated by Django 4.2.2 on 2023-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='unsubscribe_path',
            field=models.CharField(default='TBA', max_length=100),
        ),
    ]
