# Generated by Django 4.2.2 on 2023-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='not_delivered',
            field=models.IntegerField(default=0),
        ),
    ]
