# Generated by Django 4.2 on 2023-06-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='contact_list',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='message',
        ),
    ]
