# Generated by Django 4.2.2 on 2023-07-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='content_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
