# Generated by Django 4.2.2 on 2023-10-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_sms_sms_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='content_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
