# Generated by Django 4.2.2 on 2023-10-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sms_unsubscribe_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='unsubscribe_path',
            field=models.CharField(default='https://sendit-frontend-production.up.railway.app/', max_length=100),
        ),
    ]
