# Generated by Django 4.2.2 on 2023-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sms_content_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='content_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
