# Generated by Django 4.2.2 on 2024-09-29 12:18

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_sms_unique_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='button_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='button_1_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='button_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='button_2_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='button_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='button_3_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='button_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='button_4_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
