# Generated by Django 4.2.2 on 2023-10-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sms_delivered_sms_not_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
