# Generated by Django 4.2.2 on 2024-10-05 18:49

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_sms_button_1_sms_button_1_name_sms_button_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
