# Generated by Django 4.2.2 on 2023-08-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_contactlist_contact_lenght_alter_message_status'),
        ('sms', '0004_sms_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='contact_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.contactlist'),
            preserve_default=False,
        ),
    ]
