# Generated by Django 4.2.2 on 2023-11-26 12:50

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_sms_total_bounce_rate_sms_total_overall_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
