# Generated by Django 4.2.2 on 2024-10-09 18:06

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_element_unique_button_id'),
        ('sms', '0005_alter_sms_unique_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
        migrations.CreateModel(
            name='CampaignStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.IntegerField(default=0)),
                ('audience', models.IntegerField(default=0)),
                ('unsub_users', models.IntegerField(default=0)),
                ('overall_perfromance', models.IntegerField(default=0)),
                ('campaign_start', models.DateField(null=True)),
                ('campaign_end', models.DateField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.sms')),
            ],
        ),
    ]
