# Generated by Django 4.2.2 on 2023-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_sms_contact_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='sms_sends',
            field=models.IntegerField(default=0),
        ),
    ]
