# Generated by Django 4.2.2 on 2023-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_sms_sms_sends'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='click_number',
            field=models.IntegerField(default=0),
        ),
    ]
