# Generated by Django 4.2.2 on 2024-10-09 18:24

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_sms_unique_tracking_id_campaignstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstats',
            name='sms',
        ),
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
