# Generated by Django 4.2.2 on 2024-10-13 10:24

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_remove_campaignstats_sms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='campaignstats',
            name='total_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
