# Generated by Django 4.2.2 on 2023-09-13 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_sms_click_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
