# Generated by Django 4.2.2 on 2024-10-13 10:28

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_overallstats_campaignstats_total_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
