# Generated by Django 4.2.2 on 2023-09-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_sms_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
