# Generated by Django 4.2.2 on 2024-10-13 10:32

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_element_unique_button_id'),
        ('sms', '0009_alter_sms_unique_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstats',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
