# Generated by Django 4.2.2 on 2023-09-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_sms_is_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='unique_id',
            new_name='unique_tracking_id',
        ),
    ]
