# Generated by Django 4.2.2 on 2023-09-13 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_rename_unique_id_sms_unique_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
