# Generated by Django 4.2.2 on 2024-10-13 11:25

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_campaignstats_user_alter_sms_unique_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstats',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignstats',
            name='campaign_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
