# Generated by Django 4.2.2 on 2023-09-13 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_alter_sms_unique_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.UUIDField(default=uuid.UUID('e01d8173-75a0-4564-af2a-5397e486c738'), unique=True),
        ),
    ]
