# Generated by Django 4.2.2 on 2023-10-03 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_alter_sms_unique_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
