# Generated by Django 4.2.2 on 2023-12-18 15:20

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_alter_sms_unique_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='total_bounce_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='sms',
            name='total_overall_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='sms',
            name='unique_tracking_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
