# Generated by Django 4.2.16 on 2025-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('success', 'password_change'), ('success', 'purchase'), ('error', 'purchase_error'), ('error', 'send_error')], max_length=30),
        ),
    ]
