# Generated by Django 4.2.16 on 2025-12-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_optimizationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationjob',
            name='store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
