# Generated by Django 4.2.16 on 2025-12-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customuser_shopify_business_ruleset'),
        ('notification', '0003_optimizationjob_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationjob',
            name='store_id',
        ),
        migrations.AddField(
            model_name='optimizationjob',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shopifystore'),
        ),
    ]
