# Generated by Django 4.2.16 on 2025-07-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_title_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('success', 'success'), ('error', 'error')], max_length=30),
        ),
    ]
