# Generated by Django 4.2.16 on 2026-01-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_optimizationjob_store_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationjob',
            name='product_draft',
        ),
        migrations.AddField(
            model_name='optimizationjob',
            name='product_draft_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
