# Generated by Django 4.2.16 on 2025-03-28 21:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('list_name', models.CharField(max_length=20)),
                ('contact_lenght', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sms_count', models.IntegerField(default=0)),
                ('user_type', models.CharField(choices=[('Independent', 'Independent'), ('Business', 'Business'), ('Other', 'Other')], max_length=20)),
                ('custom_email', models.EmailField(max_length=254, unique=True)),
                ('last_password_change', models.DateField(blank=True, null=True)),
                ('archived_state', models.BooleanField(default=False)),
                ('welcome_mail_sent', models.BooleanField(default=False)),
                ('stripe_custom_id', models.CharField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_button_id', models.CharField(default=None, null=True)),
                ('element_type', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('alignment', models.CharField(max_length=20, null=True)),
                ('text', models.TextField(blank=True)),
                ('survey', models.CharField(max_length=50, null=True)),
                ('question_type', models.CharField(choices=[('Like/Dislike', 'Like/Dislike'), ('Question Survey', 'Question Survey')], max_length=20, null=True)),
                ('button_title', models.CharField(max_length=20, null=True)),
                ('button_link', models.CharField(max_length=100, null=True)),
                ('button_link_track', models.CharField(max_length=100, null=True)),
                ('button_color', models.CharField(default='#000000', max_length=20)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(max_length=20, null=True)),
                ('like_response', models.IntegerField(default=0, null=True)),
                ('dislike_response', models.IntegerField(default=0, null=True)),
                ('numeric_response', models.IntegerField(default=0, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.element')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('qr_data', models.CharField(default=None)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contactlist')),
            ],
        ),
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('sms_count_pack', models.IntegerField()),
                ('offer1', models.CharField(blank=True, max_length=200, null=True)),
                ('offer2', models.CharField(blank=True, max_length=200, null=True)),
                ('offer3', models.CharField(blank=True, max_length=200, null=True)),
                ('offer4', models.CharField(blank=True, max_length=200, null=True)),
                ('offer5', models.CharField(blank=True, max_length=200, null=True)),
                ('offer6', models.CharField(blank=True, max_length=200, null=True)),
                ('offer7', models.CharField(blank=True, max_length=200, null=True)),
                ('offer8', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=40)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='Draft', max_length=10, null=True)),
                ('total_overall_progress', models.IntegerField(default=0)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfirmationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='package_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.packageplan'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('contact_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contactlist')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sends', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_bounces', models.IntegerField(default=0)),
                ('total_bounce_rate', models.IntegerField(default=0)),
                ('total_overall_rate', models.IntegerField(default=0)),
                ('total_spend', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_not_delivered', models.IntegerField(default=0)),
                ('tota_unsubscribed', models.IntegerField(default=0)),
                ('tota_subscribed', models.IntegerField(default=0)),
                ('contacts_limit_reached', models.BooleanField(default=False)),
                ('contact_list_limit_reached', models.BooleanField(default=False)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
    ]
