# Generated by Django 4.2.2 on 2024-03-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sends', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_bounce_rate', models.IntegerField(default=0)),
                ('total_overall_rate', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
            ],
        ),
    ]
