# Generated by Django 4.2.2 on 2024-10-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='unique_button_id',
            field=models.CharField(default=None, null=True),
        ),
    ]
