# Generated by Django 4.2.2 on 2023-10-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='element_list',
        ),
        migrations.AddField(
            model_name='element',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.message'),
            preserve_default=False,
        ),
    ]
