# Generated by Django 4.2.2 on 2024-10-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdata',
            name='total_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdata',
            name='total_spend',
            field=models.IntegerField(default=0),
        ),
    ]
