# Generated by Django 4.2.16 on 2025-10-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='sms_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
