# Generated by Django 4.2.2 on 2023-12-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='question_type',
            field=models.CharField(choices=[('Like/Dislike', 'Like/Dislike'), ('Question Survey', 'Question Survey')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='survey',
            field=models.CharField(choices=[('Like/Dislike', 'Like/Dislike'), ('Question Survey', 'Question Survey')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_response', models.IntegerField(blank=True, null=True)),
                ('dislike_response', models.IntegerField(blank=True, null=True)),
                ('numeric_response', models.IntegerField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.element')),
            ],
        ),
    ]
