# Generated by Django 4.2 on 2023-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contactlist_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
