# Generated by Django 4.2.16 on 2024-11-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_archived_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_custom_id',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='welcome_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
