# Generated by Django 4.2.2 on 2023-11-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_message_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='hashed_phone',
        ),
    ]
