# Generated by Django 4.2.2 on 2023-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_hashed_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='hashed_phone',
            field=models.CharField(default='TBA', max_length=200),
        ),
    ]
