# Generated by Django 4.2.16 on 2025-10-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_email_opt_in_contact_sms_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_opt_in',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sms_opt_in',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
