# Generated by Django 4.2.16 on 2025-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_element_carousel_images_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image_src',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
