# Generated by Django 4.2.2 on 2023-12-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_element_question_type_element_survey_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='survey',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
