# Generated by Django 4.2.16 on 2025-04-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shopifystore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifystore',
            name='user',
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
