# Generated by Django 4.2.2 on 2024-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_analyticsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sms_count',
            field=models.IntegerField(default=0),
        ),
    ]
