# Generated by Django 4.2.2 on 2023-10-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_message_element_list_element_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='element_list',
            field=models.ManyToManyField(related_name='messages', to='base.element'),
        ),
    ]
