# Generated by Django 4.2.2 on 2023-11-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_contact_hashed_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='button_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
