# Generated by Django 4.2.16 on 2025-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_contact_email_opt_in_alter_contact_sms_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shopify_product_import',
            field=models.BooleanField(default=False),
        ),
    ]
