# Generated by Django 4.2.2 on 2024-04-19 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customuser_sms_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
