# Generated by Django 4.2.16 on 2025-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_shopifystore_user_shopifystore_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='list_name',
            field=models.CharField(max_length=50),
        ),
    ]
