# Generated by Django 4.2.16 on 2025-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_carouselimage_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image_src',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
