# Generated by Django 4.2.2 on 2023-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_element_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
