# Generated by Django 4.2.16 on 2024-11-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customuser_stripe_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdata',
            name='total_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsdata',
            name='total_not_delivered',
            field=models.IntegerField(default=0),
        ),
    ]
