# Generated by Django 4.2.2 on 2023-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_element_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='survey',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
