# Generated by Django 4.2 on 2023-07-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_packageplan_description_packageplan_offer1'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='offer2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='offer3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='offer4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='offer5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='offer6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='offer7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='offer8',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
