# Generated by Django 4.2.16 on 2025-05-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contactlist_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='num_of_customers',
            field=models.IntegerField(default=0),
        ),
    ]
