# Generated by Django 4.2 on 2023-07-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_packageplan_offer2_packageplan_offer3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageplan',
            name='offer1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='offer2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='offer3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='offer4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='offer5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='offer6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='offer7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='offer8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
