# Generated by Django 4.2.2 on 2023-12-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_element_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='dislike_response',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='like_response',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='numeric_response',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
