# Generated by Django 4.2.16 on 2025-11-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_shopify_product_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shopify_business_ruleset',
            field=models.BooleanField(default=False),
        ),
    ]
