# Generated by Django 4.2.2 on 2023-12-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_surveyresponse_dislike_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
