# Generated by Django 4.2.16 on 2025-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_shopifystore_num_of_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifystore',
            name='num_of_customers',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_list',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
