# Generated by Django 4.2.16 on 2024-11-17 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('779987b3-dd8d-408b-9f51-a78e2ac2c1e2')),
        ),
    ]
