# Generated by Django 4.2 on 2023-07-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='package_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.packageplan'),
        ),
    ]
