# Generated by Django 4.2 on 2023-05-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_note_body_note_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.note')),
            ],
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
