# Generated by Django 4.2.16 on 2025-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_carouselimage_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='custom_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
