# Generated by Django 4.2.16 on 2025-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_shopifystore_num_of_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='campaign_type',
            field=models.CharField(choices=[('Promotional', 'Promotional'), ('Notification', 'Notification')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sms_send',
            field=models.CharField(choices=[('Send', 'Send'), ('Schedule', 'Schedule')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sms_text',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
