# Generated by Django 4.2.2 on 2023-08-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='contact_lenght',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, default='Draft', max_length=10, null=True),
        ),
    ]
