# Generated by Django 4.2.16 on 2024-11-17 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contactlist_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('62f5a6ed-417a-4337-9702-70c361f6318f')),
        ),
    ]
