# Generated by Django 4.2 on 2023-05-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_imagemodel_delete_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='note',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='note',
            field=models.ManyToManyField(to='base.note'),
        ),
    ]
