# Generated by Django 4.2.16 on 2025-05-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message_campaign_type_message_sms_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='carousel_images',
            field=models.JSONField(default=list, null=True),
        ),
    ]
