# Generated by Django 4.2.2 on 2023-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_customuser_package_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='sms_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
