# Generated by Django 4.2.16 on 2024-11-17 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_contactlist_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('46d05c4f-9179-458b-8ed3-31eb0c892e1a')),
        ),
    ]
