# Generated by Django 4.2.16 on 2025-06-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_contact_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_shopify_contact',
            field=models.BooleanField(default=False),
        ),
    ]
