# Generated by Django 4.2.16 on 2025-07-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contact_is_shopify_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
