# Generated by Django 4.2.2 on 2023-12-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Independent', 'Independent'), ('Business', 'Business'), ('Other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
