# Generated by Django 4.2.16 on 2025-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_element_carousel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shopify_connect',
            field=models.BooleanField(default=False),
        ),
    ]
