# Generated by Django 4.2 on 2023-05-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_imagemodel_note_imagemodel_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AddField(
            model_name='image',
            name='note',
            field=models.ManyToManyField(to='base.note'),
        ),
    ]
