# Generated by Django 4.2.2 on 2023-07-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_packageplan_sms_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageplan',
            name='sms_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
