# Generated by Django 4.2.16 on 2024-11-23 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_contactlist_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
