# Generated by Django 4.2.2 on 2023-07-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_packageplan_sms_count_customuser_sms_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='sms_count_pack',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
