# Generated by Django 4.2.16 on 2025-06-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_customuser_shopify_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='shopify_list',
            field=models.BooleanField(default=False),
        ),
    ]
