# Generated by Django 4.2 on 2023-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_image_remove_note_image_delete_imagemodel_image_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, null=True)),
                ('note', models.ManyToManyField(to='base.note')),
            ],
        ),
    ]
