# Generated by Django 4.2.16 on 2025-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='scheduled_subscription',
            field=models.DateField(blank=True, null=True),
        ),
    ]
