# Generated by Django 4.2.16 on 2024-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_contactlist_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdata',
            name='tota_unsubscribed',
            field=models.IntegerField(default=0),
        ),
    ]
