# Generated by Django 4.2.2 on 2023-12-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
