# Generated by Django 4.2.16 on 2025-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customuser_scheduled_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='scheduled_package',
            field=models.CharField(default=None, null=True),
        ),
    ]
