# Generated by Django 4.2 on 2023-05-16 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_remove_note_text_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Message',
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ManyToManyField(related_name='element_list', to='base.message')),
            ],
        ),
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.element')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.text')),
            ],
            bases=('base.element',),
        ),
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.element')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.image')),
            ],
            bases=('base.element',),
        ),
    ]
