# Generated by Django 4.2.16 on 2024-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_analyticsdata_tota_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdata',
            name='total_bounces',
            field=models.IntegerField(default=0),
        ),
    ]
