# Generated by Django 4.2.2 on 2024-09-28 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_customuser_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='button_link_track',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='unique_button_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
