# Generated by Django 4.2.2 on 2023-07-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_packageplan_sms_count_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
