# Generated by Django 4.2 on 2023-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_note_message_element_textelement_imageelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='message',
            field=models.ManyToManyField(related_name='element_set', to='base.message'),
        ),
    ]
