# Generated by Django 4.2.16 on 2024-12-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_analyticsdata_total_bounces'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdata',
            name='contact_list_limit_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsdata',
            name='contacts_limit_reached',
            field=models.BooleanField(default=False),
        ),
    ]
