# Generated by Django 4.2.16 on 2025-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_customuser_scheduled_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
