# Generated by Django 4.2.2 on 2024-09-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_element_button_link_track_element_unique_button_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='unique_button_id',
            field=models.UUIDField(editable=False),
        ),
    ]
