# Generated by Django 4.2.16 on 2024-12-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_analyticsdata_contact_list_limit_reached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdata',
            name='tota_subscribed',
            field=models.IntegerField(default=0),
        ),
    ]
