# Generated by Django 4.2 on 2023-05-16 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_alter_message_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='message',
            field=models.ManyToManyField(related_name='element_set', to='base.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
