# Generated by Django 4.2 on 2023-05-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_element_message_alter_message_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='message',
            field=models.ManyToManyField(related_name='elements', to='base.message'),
        ),
    ]
