# Generated by Django 4.2 on 2023-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_element_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageelement',
            name='element_ptr',
        ),
        migrations.RemoveField(
            model_name='imageelement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='text',
            name='note',
        ),
        migrations.RemoveField(
            model_name='textelement',
            name='element_ptr',
        ),
        migrations.RemoveField(
            model_name='textelement',
            name='text',
        ),
        migrations.RemoveField(
            model_name='element',
            name='message',
        ),
        migrations.AddField(
            model_name='element',
            name='element_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='element',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='element_list',
            field=models.ManyToManyField(to='base.element'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageElement',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='TextElement',
        ),
    ]
