# Generated by Django 4.2 on 2023-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_imageelement_element_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='text',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
