# Generated by Django 4.2 on 2023-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_element_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
