# Generated by Django 4.2 on 2023-05-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_element_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='element_list',
            field=models.ManyToManyField(related_name='messages', to='base.element'),
        ),
    ]
