# Generated by Django 4.2 on 2023-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_message_element_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='button_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='button_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
