# Generated by Django 4.2 on 2023-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_element_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='alignment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
