# Generated by Django 4.2.16 on 2025-10-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_contact_email_opt_in_alter_contact_sms_opt_in'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_store',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='base.shopifystore'),
            preserve_default=False,
        ),
    ]
