# Generated by Django 4.2.16 on 2025-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_shopify_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_field',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
