# Generated by Django 4.2.16 on 2025-10-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopify_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
