# Generated by Django 4.2.16 on 2025-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_shopify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.BooleanField(default=False),
        ),
    ]
