# Generated by Django 4.2.16 on 2025-10-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_variants_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=99999, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
