# Generated by Django 4.2.16 on 2025-11-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_contact_email_opt_in_alter_contact_sms_opt_in'),
        ('products', '0009_product_color_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_topic', models.CharField(max_length=255)),
                ('webhook_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopify_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shopifystore')),
            ],
        ),
    ]
