# Generated by Django 4.2.16 on 2025-11-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_shopifywebhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('product_variant_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('product_tag_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('product_alt_image_rule', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completeness', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
