# Generated by Django 4.2.16 on 2025-11-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rulespattern_productscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscore',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productscore',
            name='product',
            field=models.ForeignKey(default=9999992, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='products.product'),
            preserve_default=False,
        ),
    ]
