# Generated by Django 4.2.16 on 2025-11-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productscore_product_id_productscore_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscore',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='products.product'),
        ),
    ]
