# Generated by Django 4.2.16 on 2025-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productscore_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulespattern',
            name='max_description_length',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='rulespattern',
            name='max_title_length',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='rulespattern',
            name='min_description_length',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='rulespattern',
            name='min_images',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rulespattern',
            name='min_title_length',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rulespattern',
            name='requires_alt_text',
            field=models.BooleanField(default=True),
        ),
    ]
