# Generated by Django 4.2.16 on 2025-11-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_shopify_product_import'),
        ('products', '0014_rulespattern_max_description_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulespattern',
            name='store',
            field=models.ForeignKey(default=9999921, on_delete=django.db.models.deletion.CASCADE, to='base.shopifystore'),
            preserve_default=False,
        ),
    ]
