# Generated by Django 4.2.16 on 2025-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rulespattern_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulespattern',
            name='max_alt_desc_length',
            field=models.IntegerField(default=30),
        ),
    ]
