# Generated by Django 4.2.16 on 2025-11-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rulespattern_max_alt_desc_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
