# Generated by Django 4.2.16 on 2025-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_parent_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulespattern',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
