# Generated by Django 4.2.16 on 2025-11-30 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rulespattern_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_field',
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_media_id', models.CharField(max_length=255, unique=True)),
                ('src', models.URLField(max_length=500)),
                ('alt_text', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
