# Generated by Django 4.2.16 on 2025-11-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_img_field_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_field',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
