# Generated by Django 4.2.16 on 2025-11-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customuser_shopify_business_ruleset'),
        ('products', '0021_alter_productmedia_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMediaDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_media_id', models.CharField(max_length=255, unique=True)),
                ('src', models.URLField(blank=True, max_length=500, null=True)),
                ('alt_text', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('parent_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('img_field', models.URLField(blank=True, max_length=500, null=True)),
                ('variant', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('synced_with_shopify', models.BooleanField(default=False)),
                ('shopify_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shopifystore')),
            ],
        ),
    ]
