# Generated by Django 4.2.16 on 2025-12-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productmediadraft_productdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmediadraft',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productdraft'),
        ),
    ]
