# Generated by Django 4.2.16 on 2025-12-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_productmediadraft_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulespattern',
            name='product_description_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
