# Generated by Django 4.2.16 on 2025-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rulespattern_product_description_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdraft',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
