# Generated by Django 4.2.16 on 2025-12-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_description_productdraft_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='static_desc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdraft',
            name='static_desc',
            field=models.BooleanField(default=False),
        ),
    ]
