# Generated by Django 4.2.16 on 2025-12-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_static_desc_productdraft_static_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='field_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmediadraft',
            name='field_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
