# Generated by Django 4.2.16 on 2025-12-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_productmedia_field_id_productmediadraft_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, max_length=161, null=True),
        ),
        migrations.AddField(
            model_name='productdraft',
            name='seo_description',
            field=models.TextField(blank=True, max_length=161, null=True),
        ),
    ]
