# Generated by Django 4.2.16 on 2025-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_producttagdraft_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='optimization_status',
            field=models.CharField(choices=[('in progress', 'In progress'), ('not started', 'Not started'), ('completed', 'Completed'), ('failed', 'Failed')], default='not started', max_length=20),
        ),
    ]
