# Generated by Django 4.2.16 on 2026-01-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_optimization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='optimized',
            field=models.BooleanField(default=False),
        ),
    ]
