# Generated by Django 4.2.16 on 2026-01-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_product_optimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdraft',
            name='optimization_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
