# Generated by Django 4.2.16 on 2026-01-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productdraft_optimization_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulespattern',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulespattern',
            name='product_alt_image_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulespattern',
            name='product_description_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulespattern',
            name='product_image_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulespattern',
            name='product_name_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulespattern',
            name='product_tag_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulespattern',
            name='product_variant_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
